// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2026 RAINDAYS121.
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Web.Script.Serialization;

namespace LoLMouseGuard
{
    sealed class MemoryFloatingStore : IFloatingStore
    {
        public FloatingPreferences Value=new FloatingPreferences();
        public bool Fail;
        public FloatingPreferences Load(out string warning) { warning=null; return Value.Copy(); }
        public void Save(FloatingPreferences p) { if(Fail) throw new IOException(); Value=p.Copy(); }
    }
    sealed class FakeFloatingWindow : IFloatingWindow
    {
        public bool Shown {get;private set;}
        public int Shows,Hides,Disposes,Places;
        public Rectangle Bounds;
        public View Last;
        public void Place(Rectangle r) { Places++; Bounds=r; }
        public void Present(View v) { Last=v; }
        public void ShowPassive() { Shows++; Shown=true; }
        public void HidePassive() { Hides++; Shown=false; }
        public void Dispose() { Disposes++; Shown=false; }
    }
    static class FloatingTests
    {
        static void Check(bool ok) { if(!ok) throw new Exception("assertion failed"); }
        static List<MonitorArea> Screens() { return new List<MonitorArea> { new MonitorArea { Name="primary",Work=new Rectangle(0,0,1920,1040) },new MonitorArea { Name="secondary",Work=new Rectangle(-2560,-200,2560,1440),Scale=1.5 } }; }
        static Scene SceneFor(string actual,string target)
        { return new Scene { Window=new IntPtr(42),Pid=100,Executable=actual,TargetExecutable=target,Visible=true,CoordinatesReady=true,CursorReady=true,Client=new Box(0,0,1920,1080),Monitor=new Box(0,0,1920,1080),VirtualScreen=new Box(-1920,0,1920,1080),Cursor=new Position(100,100) }; }
        public static int Append(string output)
        {
            List<SelfTests.Check> checks=new List<SelfTests.Check>();
            Action<string,Action> test=delegate(string name,Action action) { SelfTests.Check c=new SelfTests.Check {name=name}; try {action();c.passed=true;} catch(Exception e) {c.error=e.Message;} checks.Add(c); };
            test("floating_default_off_creates_no_window",delegate { MemoryFloatingStore s=new MemoryFloatingStore(); int made=0; using(FloatingController c=new FloatingController(s,delegate {made++;return new FakeFloatingWindow();})) {c.Refresh(Previews.State("paused"),Screens()); Check(!c.Preferences.Enabled && made==0);} });
            test("floating_toggle_never_changes_core_and_reuses_window",delegate {MemoryFloatingStore s=new MemoryFloatingStore(); FakeFloatingWindow w=new FakeFloatingWindow(); int made=0; View v=Previews.State("paused"); using(FloatingController c=new FloatingController(s,delegate {made++;return w;})) {Check(c.SetEnabled(true)); c.Refresh(v,Screens()); Check(!v.Enabled && ReferenceEquals(v,w.Last) && w.Shown); c.SetEnabled(false); c.Refresh(v,Screens()); Check(!w.Shown); c.SetEnabled(true); c.Refresh(v,Screens()); Check(made==1 && w.Shows==2);} Check(w.Disposes==1);});
            test("floating_uses_actual_view_for_all_states",delegate {MemoryFloatingStore s=new MemoryFloatingStore(); FakeFloatingWindow w=new FakeFloatingWindow(); using(FloatingController c=new FloatingController(s,delegate {return w;})) {c.SetEnabled(true); foreach(string kind in new[] {"paused","waiting","protected","error"}) {View v=Previews.State(kind); c.Refresh(v,Screens()); Check(ReferenceEquals(v,w.Last) && StatusPresentation.Kind(w.Last)==kind);} View changed=Previews.State("protected"); changed.Enabled=false; c.Refresh(changed,Screens()); Check(StatusPresentation.Kind(w.Last)=="paused"); changed.Editing=true;changed.CanEnable=false;Check(StatusPresentation.Kind(changed)=="paused");}});
            test("floating_stopped_disposes_once_and_never_reopens",delegate {MemoryFloatingStore s=new MemoryFloatingStore(); FakeFloatingWindow w=new FakeFloatingWindow(); FloatingController c=new FloatingController(s,delegate {return w;}); c.SetEnabled(true);c.Refresh(Previews.State("waiting"),Screens()); View ended=Previews.State("paused");ended.Stopped=true;c.Refresh(ended,Screens());c.Refresh(Previews.State("protected"),Screens());c.Dispose();Check(w.Disposes==1 && !w.Shown && !c.SetEnabled(true));});
            test("floating_failed_save_keeps_previous_visibility",delegate {MemoryFloatingStore s=new MemoryFloatingStore(); FakeFloatingWindow w=new FakeFloatingWindow(); using(FloatingController c=new FloatingController(s,delegate {return w;})) {c.SetEnabled(true);c.Refresh(Previews.State("paused"),Screens());s.Fail=true;Check(!c.SetEnabled(false) && c.Preferences.Enabled && w.Shown && c.Warning!=null);}});
            test("floating_negative_monitor_position_restores",delegate {FloatingPreferences p=new FloatingPreferences {HasPosition=true,Monitor="secondary",X=20,Y=40}; Rectangle r=FloatingGeometry.Restore(p,Screens());Check(r==new Rectangle(-2530,-140,315,45));});
            test("floating_removed_monitor_returns_to_primary",delegate {FloatingPreferences p=new FloatingPreferences {HasPosition=true,Monitor="missing",X=-300,Y=99999}; Rectangle r=FloatingGeometry.Restore(p,Screens());Check(Screens()[0].Work.Contains(r) && r.X==1690 && r.Y==20);});
            test("floating_offscreen_saved_coordinates_clamp",delegate {FloatingPreferences p=new FloatingPreferences {HasPosition=true,Monitor="primary",X=99999,Y=-99999};Rectangle r=FloatingGeometry.Restore(p,Screens());Check(r.X==1710 && r.Y==0 && Screens()[0].Work.Contains(r));});
            test("floating_dpi_position_uses_logical_offsets",delegate {List<MonitorArea> screens=Screens();FloatingPreferences p=FloatingGeometry.Capture(new FloatingPreferences(),new Rectangle(-2410,-50,222,45),screens);Check(p.Monitor=="secondary" && p.X==100 && p.Y==100);screens[1].Scale=2;Rectangle r=FloatingGeometry.Restore(p,screens);Check(r==new Rectangle(-2360,0,420,60));});
            test("floating_topology_change_recovers_without_recreating",delegate {MemoryFloatingStore s=new MemoryFloatingStore();s.Value=new FloatingPreferences {Enabled=true,HasPosition=true,Monitor="secondary",X=1400,Y=800};FakeFloatingWindow w=new FakeFloatingWindow();using(FloatingController c=new FloatingController(s,delegate {return w;})) {List<MonitorArea> screens=Screens();c.Refresh(Previews.State("paused"),screens);screens.RemoveAt(1);c.Refresh(Previews.State("paused"),screens);Check(w.Places==2 && screens[0].Work.Contains(w.Bounds) && w.Shows==1);c.ResetPosition();c.Refresh(Previews.State("paused"),screens);Check(!c.Preferences.HasPosition && w.Places==3);}});
            test("floating_move_is_saved_and_failure_has_no_state_change",delegate {MemoryFloatingStore s=new MemoryFloatingStore();FakeFloatingWindow w=new FakeFloatingWindow();View v=Previews.State("protected");using(FloatingController c=new FloatingController(s,delegate {return w;})) {c.SetEnabled(true);c.Refresh(v,Screens());c.Moved(new Rectangle(-2500,0,222,45),Screens());Check(s.Value.Monitor=="secondary" && s.Value.HasPosition);double old=s.Value.X;s.Fail=true;c.Moved(new Rectangle(500,500,148,30),Screens());Check(c.Preferences.X==old && c.Warning!=null && v.Enabled && v.Status=="保护中");}});
            test("floating_json_roundtrip_replace_and_corrupt_fallback",delegate {string dir=Path.Combine(Path.GetDirectoryName(output),"floating-test-"+Guid.NewGuid().ToString("N")),file=Path.Combine(dir,"floating.json");try {FloatingFileStore s=new FloatingFileStore(file);string warning;Check(!s.Load(out warning).Enabled && warning==null);s.Save(new FloatingPreferences {Enabled=true,HasPosition=true,Monitor="secondary",X=-23,Y=100});FloatingPreferences p=s.Load(out warning);Check(warning==null && p.Enabled && p.X==-23);s.Save(new FloatingPreferences());Check(!s.Load(out warning).Enabled && Directory.GetFiles(dir).Length==1);File.WriteAllText(file,"{broken",Encoding.UTF8);Check(!s.Load(out warning).Enabled && warning!=null);}finally {if(File.Exists(file)) File.Delete(file);if(Directory.Exists(dir) && Directory.GetFiles(dir).Length==0) Directory.Delete(dir);}});
            test("floating_invalid_coordinates_rejected",delegate {Check(!new FloatingPreferences {X=Double.NaN}.Valid && !new FloatingPreferences {Y=Double.PositiveInfinity}.Valid && !new FloatingPreferences {Version=2}.Valid);});
            test("selected_game_strict_name_and_visibility",delegate {Box t;Scene s=SceneFor("ExampleGame.exe","ExampleGame.exe");Check(s.TryTarget(out t));s.Executable="ExampleGame.exe.bak";Check(!s.TryTarget(out t));s.Executable="OtherGame.exe";Check(!s.TryTarget(out t));s.Executable="EXAMPLEGAME.EXE";Check(s.TryTarget(out t));s.Minimized=true;Check(!s.TryTarget(out t));s.Minimized=false;s.Pid=0;Check(!s.TryTarget(out t));});
            test("selected_game_focus_loss_releases_and_returns_after_stability",delegate {FakeBackend b=new FakeBackend();GuardCore c=new GuardCore(b,true);c.SetHotkeys(true,null);c.Enable();Scene s=SceneFor("ExampleGame.exe","ExampleGame.exe");c.Step(s,0);c.Step(s,100);Check(b.Applies==1);s.Executable="League of Legends.exe";c.Step(s,101);Check(b.Frees==1 && !c.OwnsClip);s.Executable="ExampleGame.exe";c.Step(s,102);c.Step(s,202);Check(b.Applies==2);c.Stop();});
            test("target_setting_roundtrip_legacy_and_invalid_names",delegate {Settings s=Settings.Defaults();s.TargetExecutable="Example Game.exe";Check(s.Validate()==null && s.Copy().TargetExecutable==s.TargetExecutable);foreach(string name in new[] {"","*Game.exe","C:\\Game.exe","Game.exe\n","Game","../Game.exe"}) {s.TargetExecutable=name;Check(s.Validate()!=null);}JavaScriptSerializer j=new JavaScriptSerializer();Settings legacy=j.Deserialize<Settings>("{\"Toggle\":{\"Modifiers\":3,\"Key\":119},\"Emergency\":{\"Modifiers\":3,\"Key\":120},\"Exit\":{\"Modifiers\":3,\"Key\":121},\"StartWithWindows\":false}");Check(legacy.TargetExecutable=="League of Legends.exe" && legacy.Validate()==null);});
            test("target_change_does_not_rewrite_existing_startup_path",delegate {FakeBackend b=new FakeBackend();MemorySettingsStore store=new MemorySettingsStore();store.Value.StartWithWindows=true;MemoryStartupStore startup=new MemoryStartupStore();startup.Values["LoLMouseGuard"]="old-path --tray";using(SettingsService service=new SettingsService(b,store,startup,@"C:\Example\New.exe",store.Value)) {string msg;Check(service.RegisterCurrent(out msg));service.BeginEdit();Settings next=store.Value.Copy();next.TargetExecutable="ExampleGame.exe";Check(service.Save(next,out msg) && startup.Writes==0 && startup.Read()=="old-path --tray" && service.Current.TargetExecutable=="ExampleGame.exe");}});
            test("failed_target_save_restores_previous_target_and_hotkeys",delegate {FakeBackend b=new FakeBackend();MemorySettingsStore store=new MemorySettingsStore {Fail=true};MemoryStartupStore startup=new MemoryStartupStore();using(SettingsService service=new SettingsService(b,store,startup,@"C:\Example\Guard.exe",store.Value)) {string msg;Check(service.RegisterCurrent(out msg));service.BeginEdit();Settings next=store.Value.Copy();next.TargetExecutable="ExampleGame.exe";Check(!service.Save(next,out msg) && service.Current.TargetExecutable=="League of Legends.exe" && b.Registered.Count==3 && startup.Writes==0);}});
            test("tray_ico_has_all_requested_sizes_and_transparency",delegate {foreach(string kind in new[] {"paused","waiting","protected","error"}) {byte[] bytes=TrayIcons.Ico(kind);Check(BitConverter.ToUInt16(bytes,2)==1 && BitConverter.ToUInt16(bytes,4)==4);for(int i=0;i<4;i++) Check(bytes[6+16*i]==TrayIcons.Sizes[i]);using(Bitmap b=TrayIcons.Draw(kind,16)) Check(b.GetPixel(0,0).A==0);}});
            test("appearance_independent_app_and_taskbar_theme",delegate {Check(ThemeChoice.IsDark("system",false) && !ThemeChoice.IsDark("system",true));Check(ThemeChoice.IsDark("dark",true) && !ThemeChoice.IsDark("light",false));using(Bitmap light=TrayIcons.Draw("paused",16,false,false)) using(Bitmap dark=TrayIcons.Draw("paused",16,true,false)) {bool differs=false;for(int x=0;x<16;x++)for(int y=0;y<16;y++)if(light.GetPixel(x,y)!=dark.GetPixel(x,y)) differs=true;Check(differs);}});
            test("appearance_save_and_failure_preserves_position_and_visibility",delegate {MemoryFloatingStore s=new MemoryFloatingStore();s.Value=new FloatingPreferences {Enabled=true,HasPosition=true,Monitor="secondary",X=100,Y=200};using(FloatingController c=new FloatingController(s,delegate {return new FakeFloatingWindow();})) {Check(c.SetAppearance("dark") && c.Preferences.Enabled && c.Preferences.X==100 && s.Value.Appearance=="dark");s.Fail=true;Check(!c.SetAppearance("light") && c.Preferences.Appearance=="dark");Check(!c.SetAppearance("invalid"));}});
            test("appearance_json_roundtrip_and_legacy_defaults_to_system",delegate {JavaScriptSerializer j=new JavaScriptSerializer();FloatingPreferences old=j.Deserialize<FloatingPreferences>("{\"Version\":1,\"Enabled\":false,\"HasPosition\":false,\"X\":0,\"Y\":0}");Check(old.Valid && old.Appearance=="system");old.Appearance="dark";FloatingPreferences loaded=j.Deserialize<FloatingPreferences>(j.Serialize(old));Check(loaded.Valid && loaded.Appearance=="dark");});
            test("theme_palette_changes_without_changing_guard_state",delegate {View v=Previews.State("protected");Theme.Apply(false,false);Color before=Theme.Background;Theme.Apply(true,false);Check(Theme.Background!=before && StatusPresentation.Kind(v)=="protected" && v.Enabled);Theme.Apply(false,true);Check(Theme.Background==SystemColors.Window && Theme.Text==SystemColors.WindowText);Theme.Apply(false,false);});
            test("target_name_status_and_long_name_tooltip_stay_independent",delegate {View v=Previews.State("protected");Check(StatusPresentation.Name(v)=="League of Legends");v.Settings.TargetExecutable=new string('A',110)+".exe";v.ActiveExecutable=v.Settings.TargetExecutable;Check(StatusPresentation.Name(v)==new string('A',110) && StatusPresentation.Full(v).Contains(v.Settings.TargetExecutable) && StatusPresentation.Short(v)=="保护中");v.Enabled=false;Check(StatusPresentation.Short(v)=="已暂停");v.Settings.TargetExecutable="OtherGame.exe";v.ActiveExecutable=v.Settings.TargetExecutable;Check(StatusPresentation.Name(v)=="OtherGame" && StatusPresentation.Full(v).StartsWith("OtherGame.exe"));v.Settings.TargetExecutable=@"C:\Synthetic\League of Legends.EXE";v.ActiveExecutable=v.Settings.TargetExecutable;Check(StatusPresentation.Name(v)=="League of Legends" && StatusPresentation.Full(v).StartsWith("League of Legends.EXE") && !StatusPresentation.Full(v).Contains("Synthetic"));});
            test("compact_short_names_reduce_width_and_long_names_keep_controls",delegate {foreach(bool floating in new[] {false,true}) {CompactBarLayout small=floating?CompactBarLayout.Floating("Paint"):CompactBarLayout.ForMain("Paint"),normal=floating?CompactBarLayout.Floating("League of Legends"):CompactBarLayout.ForMain("League of Legends"),large=floating?CompactBarLayout.Floating(new string('W',240)):CompactBarLayout.ForMain(new string('W',240));Check(small.Width<normal.Width && normal.Width<=large.Width && large.Width<=(floating?210:320));foreach(CompactBarLayout r in new[] {small,normal,large}) {Check(r.SeparatorX-r.NameX-r.NameWidth<=4 && r.StatusX>r.NameX+r.NameWidth && r.StatusX+r.StatusWidth<r.Width);if(!floating) Check(r.FirstDividerX>=r.StatusX+r.StatusWidth && r.ToggleX+40<r.SecondDividerX && r.SettingsX+26<=r.Width);}}});
            test("floating_target_resize_preserves_status_position_and_window",delegate {MemoryFloatingStore s=new MemoryFloatingStore();FakeFloatingWindow w=new FakeFloatingWindow();View v=Previews.State("paused");v.ActiveExecutable=v.Settings.TargetExecutable;v.Settings.TargetDisplay="name";using(FloatingController c=new FloatingController(s,delegate {return w;})) {c.SetEnabled(true);c.Refresh(v,Screens());int normal=w.Bounds.Width;v.Enabled=true;v.Status="保护中";c.Refresh(v,Screens());Check(w.Places==1 && w.Bounds.Width==normal);v.Settings.TargetExecutable="Paint.exe";v.ActiveExecutable=v.Settings.TargetExecutable;c.Refresh(v,Screens());Check(w.Places==2 && w.Bounds.Width<normal && Screens()[0].Work.Contains(w.Bounds) && w.Shows==1 && StatusPresentation.Kind(v)=="protected");v.Settings.TargetExecutable=new string('W',200)+".exe";v.ActiveExecutable=v.Settings.TargetExecutable;c.Refresh(v,Screens());Check(w.Places==3 && w.Bounds.Width<=210 && Screens()[0].Work.Contains(w.Bounds));}});
            test("adaptive_name_layout_at_125_150_200_dpi_keeps_click_targets_inside",delegate {foreach(string name in new[] {"Paint.exe","League of Legends.exe",new string('W',200)+".exe"}) foreach(float scale in new[] {1.25f,1.5f,2f}) {View v=Previews.State("waiting");v.Settings.TargetExecutable=name;v.ActiveExecutable=name;using(ControlPanel form=new ControlPanel(new PreviewSession(v),true,false)) using(Bitmap bitmap=form.RenderPreview(scale)) {Check(bitmap.Width<=(int)Math.Round(320*scale) && bitmap.Height==(int)Math.Round(44*scale) && !form.IsHandleCreated);foreach(System.Windows.Forms.Control child in form.Controls) if(child.AccessibleName=="设置" || child.AccessibleName=="启用或暂停鼠标保护") Check(form.ClientRectangle.Contains(child.Bounds) && child.Width>=(int)Math.Round(26*scale) && child.Height>=(int)Math.Round(24*scale));form.PreviewSettings();Check(Math.Abs(form.ClientSize.Width-380*scale)<=1 && Math.Abs(form.ClientSize.Height-402*scale)<=1 && !form.IsHandleCreated);}using(FloatingBar bar=new FloatingBar(true)) {bar.Present(v);using(Bitmap bitmap=bar.PreviewBitmap(scale)) Check(bitmap.Width<=(int)Math.Round(210*scale) && bitmap.Height==(int)Math.Round(30*scale) && !bar.IsHandleCreated);}}});
            test("adaptive_floating_width_clamps_on_negative_monitor_and_dpi_change",delegate {List<MonitorArea> screens=Screens();FloatingPreferences p=new FloatingPreferences {HasPosition=true,Monitor="secondary",X=99999,Y=100};Rectangle r=FloatingGeometry.Restore(p,screens,130);Check(screens[1].Work.Contains(r) && r.Width==195 && r.Height==45);screens[1].Scale=2;r=FloatingGeometry.Restore(p,screens,130);Check(screens[1].Work.Contains(r) && r.Width==260 && r.Height==60);});
            test("program_file_selection_keeps_only_executable_name",delegate {Check(ProgramSelection.FromFile(@"C:\Example Folder\ExampleGame.exe")=="ExampleGame.exe");bool rejected=false;try {ProgramSelection.FromFile(@"C:\Example\other.txt");}catch(ArgumentException) {rejected=true;}Check(rejected);ProgramCandidate c=new ProgramCandidate {Title="Ephemeral window title",Executable="ExampleGame.exe",Pid=100};Check(c.ToString().Contains(c.Executable));});
            test("target_file_persistence_and_legacy_config_keep_custom_keys",delegate {string directory=Path.Combine(Path.GetDirectoryName(output),"target-test-"+Guid.NewGuid().ToString("N")),file=Path.Combine(directory,"settings.json");try {FileSettingsStore store=new FileSettingsStore(file);Settings s=Settings.Defaults();s.TargetExecutable="ExampleGame.exe";s.Toggle=new Shortcut(6,0x41);store.Save(s);string warning;Settings loaded=store.Load(out warning);Check(warning==null && loaded.TargetExecutable=="ExampleGame.exe" && loaded.Toggle.Key==0x41);JavaScriptSerializer j=new JavaScriptSerializer();Dictionary<string,object> fields=j.Deserialize<Dictionary<string,object>>(File.ReadAllText(file,Encoding.UTF8));fields["Version"]=1;fields.Remove("TargetExecutables");fields.Remove("TargetExecutable");File.WriteAllText(file,j.Serialize(fields),Encoding.UTF8);loaded=store.Load(out warning);Check(warning==null && loaded.TargetExecutable=="League of Legends.exe" && loaded.Toggle.Key==0x41);}finally {if(File.Exists(file)) File.Delete(file);if(Directory.Exists(directory) && Directory.GetFiles(directory).Length==0) Directory.Delete(directory);}});
            test("custom_target_resize_and_new_foreground_instance_recompute",delegate {FakeBackend b=new FakeBackend();GuardCore core=new GuardCore(b,true);core.SetHotkeys(true,null);core.Enable();Scene s=SceneFor("ExampleGame.exe","ExampleGame.exe");core.Step(s,0);core.Step(s,100);s.Client=new Box(200,100,1000,700);s.Cursor=new Position(300,200);core.Step(s,101);Check(b.Frees==1 && b.Applies==1);core.Step(s,201);Check(b.Clip.Equals(s.Client));s.Window=new IntPtr(43);s.Pid=101;core.Step(s,202);Check(b.Applies==2 && b.Frees==2);core.Step(s,302);Check(b.Applies==3);core.Stop();});
            test("floating_effective_window_styles_and_mouse_activation_response",delegate {using(FloatingBar bar=new FloatingBar(true)) {System.Reflection.BindingFlags flags=System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic;System.Windows.Forms.CreateParams p=(System.Windows.Forms.CreateParams)typeof(FloatingBar).GetProperty("CreateParams",flags).GetValue(bar,null);Check((p.ExStyle&0x08000000)!=0 && (p.ExStyle&0x80)!=0 && !bar.ShowInTaskbar);Check((bool)typeof(FloatingBar).GetProperty("ShowWithoutActivation",flags).GetValue(bar,null));System.Windows.Forms.Message m=System.Windows.Forms.Message.Create(IntPtr.Zero,0x21,IntPtr.Zero,IntPtr.Zero);object[] args={m};typeof(FloatingBar).GetMethod("WndProc",flags).Invoke(bar,args);Check(((System.Windows.Forms.Message)args[0]).Result==new IntPtr(3) && !bar.IsHandleCreated);}});
            int failed=checks.FindAll(delegate(SelfTests.Check c) {return !c.passed;}).Count;
            JavaScriptSerializer serializer=new JavaScriptSerializer();var report=serializer.Deserialize<Dictionary<string,object>>(File.ReadAllText(output,Encoding.UTF8));
            report["floating_and_target_tests"]=checks;report["passed"]=Convert.ToInt32(report["passed"])+checks.Count-failed;report["failed"]=Convert.ToInt32(report["failed"])+failed;
            report["floating_validation"]="fake lifecycle and geometry; physical drag/focus, real DPI switches, exclusive-fullscreen visibility remain unverified";
            File.WriteAllText(output,serializer.Serialize(report),new UTF8Encoding(false));return failed==0?0:1;
        }
    }
}


